/*
=========================================================
PROJECT: Logistics Network Performance Analytics
DATABASE: PostgreSQL
PHASE: Advanced Queries

OBJECTIVE:
Understand the overall logistics operations through
high-level KPIs before diving into business analysis.

Author : Meet Shah
=========================================================
*/

/*-------------------------------------------------------
Which customers generate the highest total revenue, and how 
do they rank compared to other customers?

Objective:
This analysis helps management prioritize strategic customer relationships, 
allocate resources effectively, and recognize customers who contribute the 
most to overall business performance.
*/-------------------------------------------------------
WITH customer_revenue AS (
    SELECT
        c.customer_id,
        c.customer_name,
        SUM(l.revenue) AS total_revenue
    FROM customers c
    JOIN loads l
        ON c.customer_id = l.customer_id
    GROUP BY c.customer_id, c.customer_name)
SELECT
    customer_name,
    ROUND(total_revenue,2) AS total_revenue,
    RANK() OVER (ORDER BY total_revenue DESC) AS customer_rank
FROM customer_revenue
ORDER BY customer_rank
LIMIT 10;

/*-------------------------------------------------------
How can customers be categorized based on the total revenue they generate?

Objective:
Segment customers into revenue categories (Gold, Silver, Bronze) to support 
customer relationship management and business strategy.
*/-------------------------------------------------------
WITH customer_revenue AS (
    SELECT
        c.customer_name,
        SUM(l.revenue) AS total_revenue
    FROM customers c
    JOIN loads l
        ON c.customer_id = l.customer_id
    GROUP BY c.customer_name)
SELECT
    customer_name,
    ROUND(total_revenue,2) AS total_revenue,
    CASE
        WHEN total_revenue >= 1400000 THEN 'Gold'
        WHEN total_revenue >= 1200000 THEN 'Silver'
        ELSE 'Bronze'
    END AS customer_category
FROM customer_revenue
ORDER BY total_revenue DESC;

/*-------------------------------------------------------
How does cumulative revenue increase as customers
are ranked from highest to lowest revenue?

Objective:
Track cumulative revenue contribution to identify
how quickly revenue accumulates across customers.
*/-------------------------------------------------------
WITH customer_revenue AS (
    SELECT
        c.customer_name,
        SUM(l.revenue) AS total_revenue
    FROM customers c
    JOIN loads l
        ON c.customer_id = l.customer_id
    GROUP BY c.customer_name)
SELECT
    customer_name,
    ROUND(total_revenue,2) AS total_revenue,
    ROUND(
        SUM(total_revenue) OVER(
            ORDER BY total_revenue DESC),2) AS running_total
FROM customer_revenue
ORDER BY total_revenue DESC;

/*-------------------------------------------------------
How do shipment volume and revenue compare across
different booking types?

Objective:
Create a pivot-style report to compare shipment
volume and revenue generated by each booking type.
*/-------------------------------------------------------
SELECT
    COUNT(CASE
        WHEN booking_type = 'Contract'
        THEN load_id
    END) AS contract_shipments,
    ROUND(SUM(CASE
        WHEN booking_type = 'Contract'
        THEN revenue
    END),2) AS contract_revenue,
    COUNT(CASE
        WHEN booking_type = 'Dedicated'
        THEN load_id
    END) AS dedicated_shipments,
    ROUND(SUM(CASE
        WHEN booking_type = 'Dedicated'
        THEN revenue
    END),2) AS dedicated_revenue,
    COUNT(CASE
        WHEN booking_type = 'Spot'
        THEN load_id
    END) AS spot_shipments,
    ROUND(SUM(CASE
        WHEN booking_type = 'Spot'
        THEN revenue
    END),2) AS spot_revenue
FROM loads;